spring:
    config:
        activate:
            on-profile: dev

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/checkin-dev?allowMultiQueries=true&characterEncoding=UTF-8
        username: username
        password: password
        hikari:
            pool-name: HikariPool
            maximum-pool-size: 10
